### ISSUE TITLE
子查询问题

### ISSUE THREAD

**Issue by napuping** [wjw465150/Querydsl-Reference-Guide-Chinese-version#1]
请问大佬，像select * from (select * from xx)这种子查询用querydsl该如何实现呢?

**Comment by wjw465150** [comment]
很简单啊!
![20230220201900](https://user-images.githubusercontent.com/927155/220105212-e207134e-9133-4f64-ae52-4cf8a8f7f6f3.jpg)

**Comment by wjw465150** [comment]
使用JPASubQuery就行

**Comment by napuping** [comment]
大神，我们现在使用的是4.1.4，里面貌似没有JpaSubQuery的类







在 2023-02-20 20:20:14，"W.Stone" ***@***.***> 写道：

使用JPASubQuery就行

**Comment by wjw465150** [comment]
4的是用`JPAExpressions`
例子1:
```
JPAQuery<Tuple> query = new JPAQuery<Tuple>(em);  

query.from(room) 
     .where(room.nRoomId.notIn
                     (JPAExpressions.select(roomDepartmentMapping.nRoomId)
                           .from(roomDepartmentMapping)
                     )
           );
```
例子2:
```
    QProfessor professor = new QProfessor("e");
    
    QProfessor d = new QProfessor("d");
    
    List<Professor> list = query().select(professor).from(professor).where(professor.salary.lt(
        ExpressionUtils.all(
            JPAExpressions.select(d.salary).from(professor.directs ,d)
            )
        )).fetch();
    
    for (Professor p : list) {
      printResult(p);
    }
```

**Comment by napuping** [comment]
我想写这样from中的子句，形如: select * from (select * from xx) tmp, 这种



在 2023-02-21 10:18:22，"W.Stone" ***@***.***> 写道：

4的是用JPAExpressions
例子1:

JPAQuery<Tuple> query = new JPAQuery<Tuple>(em);  



query.from(room) 

     .where(room.nRoomId.notIn

                     (JPAExpressions.select(roomDepartmentMapping.nRoomId)

                           .from(roomDepartmentMapping)

                     )

           );



例子2:

    QProfessor professor = new QProfessor("e");

    

    QProfessor d = new QProfessor("d");

    

    List<Professor> list = query().select(professor).from(professor).where(professor.salary.lt(

        ExpressionUtils.all(

            JPAExpressions.select(d.salary).from(professor.directs ,d)

            )

        )).fetch();

    

    for (Professor p : list) {

      printResult(p);

    }

**Comment by wjw465150** [comment]
直接JPAExpressions.from就行啊
```
query.from(room)

.where(room.nRoomId.notIn

(JPAExpressions.from(roomDepartmentMapping)
```
